version: '3.7'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: userdb
      WORDPRESS_DB_PASSWORD: userpwd
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 33066:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wpdb
      MYSQL_USER: userdb
      MYSQL_PASSWORD: userpwd
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db:


